spring.application.name=Financas 2.0
spring.datasource.url=jdbc:postgresql://localhost:5432/financas
#user
spring.datasource.username=oasc
#password password
spring.datasource.password=1996

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Outras configurações do JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exceptions
server.error.include-stacktrace=never
server.error.include-message=always

server.port=${PORT:8080}